BUSCAIMOVEIS:
  DEBUG: false
  RELOADER: true
  SECRET_KEY: 's3cret'
  HOST: '0.0.0.0'
  PORT: 5000
  DATABASE_URL: 'mongodb://localhost:27017'
  DATABASE_NAME: buscaimoveis

  EXTENSIONS:
    - buscaimoveis.ext.database.configure
    - buscaimoveis.ext.auth.configure
    - buscaimoveis.ext.debug.configure
    - buscaimoveis.ext.ads.configure
    - flask_bootstrap.Bootstrap

  DEBUG_TOOLBAR_ENABLED: false
  DEBUG_TB_INTERCEPT_REDIRECTS: false
  DEBUG_TB_PROFILER_ENABLED: true
  DEBUG_TB_TEMPLATE_EDITOR_ENABLED: true

  SIMPLE_LOGIN_HOME_URL: /admin
