BUSCABIKE:
  DEBUG: false
  RELOADER: true
  SECRET_KEY: 's3cret'
  HOST: '0.0.0.0'
  PORT: 5000
  DATABASE_URL: 'mongodb://localhost:27017'
  DATABASE_NAME: buscabike

  EXTENSIONS:
    - buscabike.ext.database.configure
    - buscabike.ext.auth.configure
    - buscabike.ext.analytics.configure
    - buscabike.ext.debug.configure
    - buscabike.ext.ads.configure
    - flask_bootstrap.Bootstrap

  ANALYTICS_ENABLED: false
  ANALYTICS_SITE_ID: ''

  DEBUG_TB_ENABLED: false
  DEBUG_TB_INTERCEPT_REDIRECTS: false
  DEBUG_TB_PROFILER_ENABLED: true
  DEBUG_TB_TEMPLATE_EDITOR_ENABLED: true

  SIMPLE_LOGIN_HOME_URL: /admin
